export const EL_CLIENTE = {
  menuClientes: 'div[data-cy="menu-item-contacts"]',
  botaoNovoCliente: 'div[data-cy="contacts-wrapper-btn-new-contact"]',
  opcaoNovoClientePessoa: 'li[data-cy="contacts-wrapper-dropdown-person"]',
  modalFormNovaPessoa: 'span[data-cy="new-person-modal-title"]',
  titulomodalFormNovaPessoa: 'Nova pessoa',
  inputFormNomePessoa: 'input[data-cy="field-key-contact_name"]',
  inputFormTelefone: 'input[id="phone-field"]',
  inputFormEmail: 'input[data-cy="field-key-contact_email"]',
  inputFormCargo: 'input[id="select-fk-contactrole-23"]',
  inputFormDepartamento: 'input[id="select-fk-contactdepartment-24"]',
  itemFormSelect: 'li[class="suggestion-item"]',
  botaoFormSalvar: 'button[class="button button-action pull-right"]',
  tituloNomeCliente: 'div[id="new-contact-page-side-contact-name"]',
  opcaoTodasAsPessoas: 'Todas as pessoas',
  tabelaDinamica: 'table[id="dynamic-table"]',
  botaoDropDownEditarCliente: 'a[class="button button-white-light-border dropdown-toggle nowrap"]',
  opcaoDropDownLink: 'a[class="white-dropdown-link"]',
  modalDeConfirmacao: 'h4[class="modal-title"]',
  botaoConfirmarModal: 'a[data-cy="confirm-modal-confirm-button"]',
  tostMessage: 'div[class="toast-message"]'
};
